### ISSUE TITLE
Headline Anchor - Change Icon

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#115]
For this plugin (used in Wiki), the Icon should be changed:
https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/widgets/richtext/ProsemirrorRichText.php#L45

- change the pilcrow icon for the fa-chain icon

when user clicks the fa-chain-icon then
- link is automatically pasted into clipboard and
- scroll (as it is)
- snackbar on the bottom appears with message: Copied to clipboard. Design is the typical green checkmark and text.
- 
<img width="799" alt="256455658-d8d4969d-14da-4fb2-a2e1-7f9def5e69fb" src="https://github.com/humhub/humhub-prosemirror/assets/4736168/521c8739-38e8-4ba3-a2f5-1590db6f2eb5">

**Comment by yurabakhtin** [comment]
> - snackbar on the bottom appears with message: Copied to clipboard. Design is the typical green checkmark and text.

I am not sure this point can be done from the `humhub-prosemirror` side, because it works by using of this separate module https://github.com/humhub/humhub/blob/master/static/js/humhub/humhub.ui.status.js with code like this:

```js
humhub.modules.ui.status.success('Copied')
```

and the text `Copied` should be translatable, it may be defined in some option on init the RichText field.

or example here https://github.com/humhub/humhub/blob/master/protected/humhub/modules/content/resources/js/humhub.content.js#L15:

```
var status = require('ui.status');
status.error(response.response.error);
```
