### ISSUE TITLE
[v1.16] Use of FileHandler 

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-prosemirror#121]
# Create File Handler

![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/38e5436e-c945-4ab4-82ad-ad32b44b06d2)
![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/5302d54f-93c5-4731-8198-b0a246ce7a1c)

# Open File Handler

Also in RichtText embedded files, should be open using the FileHandler Open Dialog, instead of immediately start the download. 

![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/2ce0df6f-5736-4c1d-8170-ec6e748ee869)
![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/65caf469-f22a-4d6d-9c05-6dfd9e799aa9)

**Comment by spoorun** [comment]
That would be great, though 'insert rule' (horizontal line insert) would need a separate a new separate entry

**Comment by yurabakhtin** [comment]
@luke- What I have researched:

- The menu buttons "Upload", "Image", "Horizontal rule" are implemented as separate prosemirror plugins, e.g. https://github.com/humhub/humhub-prosemirror/tree/master/src/editor/core/plugins/upload
- The creating/uploading new file from HumHub side uses own JS, e.g. to upload simple file the JS method `file.upload` https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/resources/js/humhub.file.js#L565 is called, and on the finish uploading a result is inserted into the preview block where we see what file was uploaded and have an icon to delete it.
- Also other custom JS methods are loaded from external modules, like OnlyOffice uses `onlyoffice.createSubmit`.
- If we will call the JS methods(without modification) from the RichText editor then result will be inserted into the preview area under form and not in the editor area as expected. I.e. the methods should be modified somehow, I cannot know how it will be easy.
- I think it will be not easy to implement the integration, at least the integration will not be automatically for each module, i.e. for each module like OnlyOffice we should create the integration separately.

I see another approach:

- As I understand main request is to allow instead of direct downloading we should allow to display the File Handler Dialog with button "View file", "Download", etc., if yes then:
- we could add new icon(+) for each uploaded file like this:

![insert-icon](https://github.com/humhub/humhub-prosemirror/assets/6995524/9cf55358-d480-484d-95aa-03657faf286d)

- on click it we will insert a tag like `[test.docx](file-guid-view:5759ded6-e54c-4f01-b078-76f8cb1d09a8)`, this tag will be converted to link to open the File Handler Dialog,
- please note currently file markdown tag has structure like `[test.docx](file-guid:5759ded6-e54c-4f01-b078-76f8cb1d09a8)`, I suggest to introduce new different like `file-guid-view` or `view-guid` or some other, so such new special file tag will be converted to view file link with html like:
- `<a href="/file/view?guid=fed18c94-89c8-465f-b426-a4c637c8fa81" data-target="#globalModal">test.docx</a>` instead of:
- `<a href="/file/file/download?guid=5759ded6-e54c-4f01-b078-76f8cb1d09a8">test.docx</a>`

So what we have to do to implement this solution:
- add the new (+) icon (from core side)
- implement JS code to insert a file markdown tag with new flag like `view-guid` directly into the current cursor position of RichText editor. (I think the JS code can be implemented from HumHub core side, and it will works for all files uploaded or created by any external module.)
- Parse new file tags with `view-guid` to link with url to `/file/view?guid=`. I think small changes will be required from Prosemirror render side.
- Some changes might be needed in `humhub\modules\content\widgets\richtext\converter\RichTextToHtmlConverter` to parse the new tags, but from `RichTextToEmailHtmlConverter` we need to parse new tags as old because no need(it is impossible) to open the File Handler Dialog from email side.

**Comment by luke-** [comment]
@yurabakhtin Thanks for the research.

Hmm, I'm not a big fan of the solution, that we always need to upload the file to the file list first and then add it to the Markdown editor.

Some arguments against this:

- it requires an extra step
- on large Markdown documents e.g. Wiki Page the file section below is not always visible
- some Markdown Fields e.g. Calendar Description don't have an extra file section
- Not sure on the long run we have in Posts these two file upload options (Button and Upload File in Markdown)

Without digging deeper into the code, we need two parts:

1. A ProseMirror Plugins which adds a dropdown with all available create file handlers. When click, the File Handler Modal is opend.
2. ProseMirror needs to detect a newly created file e.g. via events done here: https://github.com/humhub/text-editor/blob/main/resources/js/humhub.text_editor.js#L51 - and should inject a Markdown link as suggested.
  
Do you think we can use the existing event? We may also have to introduce a new event here and refactor the FileHandler a little.

**Comment by yurabakhtin** [comment]
@luke- 

> Some arguments against this:
> 
> * it requires an extra step
> * on large Markdown documents e.g. Wiki Page the file section below is not always visible
> * some Markdown Fields e.g. Calendar Description don't have an extra file section
> * Not sure on the long run we have in Posts these two file upload options (Button and Upload File in Markdown)

Ok, I agree with it.

> Without digging deeper into the code, we need two parts:
> 
> 1. A ProseMirror Plugins which adds a dropdown with all available create file handlers. When click, the File Handler Modal is opend.
> 2. ProseMirror needs to detect a newly created file e.g. via events done here: https://github.com/humhub/text-editor/blob/main/resources/js/humhub.text_editor.js#L51 - and should inject a Markdown link as suggested.
> 
> Do you think we can use the existing event? We may also have to introduce a new event here and refactor the FileHandler a little.

Yes, it seems w can try to use the JS event `humhub:file:created`, also I find another event `humhub:file:created.cfiles`. We need to investigate deeply how to handle a file after uploading and how we can insert it into the richtext editor.
I guess if we will implement the inserting inline tag into richtext editor through new ProseMirror Plugin, then original event will continue inserts an uploaded file into the uploading area under form as it was before, i.e. result of the uploaded file will be displayed in two places.

**Comment by yurabakhtin** [comment]
@luke- I have started this in PR https://github.com/humhub/humhub-prosemirror/pull/134:

![file-handlers](https://github.com/humhub/humhub-prosemirror/assets/6995524/b0e2b795-02c3-4346-8d86-d7901e2e88a5)

The links are just copied from the dropdown and action `link.click()` is called, i.e. the new added menu items work as original, we still need find a solution how to process result on event `humhub:file:created`.

**Comment by luke-** [comment]
@yurabakhtin Thanks, looks good.

**Comment by yurabakhtin** [comment]
@luke- Currently I could implement only this way:

![file-handler](https://github.com/humhub/humhub-prosemirror/assets/6995524/552079fd-5349-442c-9f9d-e85fcda95bce)

I have 2 problems:

- When the form is submitted from from Modal Window I don't know how to know it was called from RichText editor and not from normal file handler. For example, the "Save" button calls js function `documenta.createSubmit()`, i.e. it seems we need to have additional fix from each File Handler because I don't imagine how to do this only from the Prosemirror side.
- `[Word.docx](file-guid:090a402a-50e1-464a-83fa-39250b261123)` - we should create some additional option to know the markdown link will be converted to link for viewing instead of current/default downloading url, maybe like `[Word.docx](file-guid:090a402a-50e1-464a-83fa-39250b261123 mode=view)` but I am not sure how it is possible from markdown parser, if it is, then we should add the `mode=view` for each link which is inserted by new plugin, but we need firstly solve the 1st point above.

**Comment by yurabakhtin** [comment]
From discussion: Set global var on click file handler and on Normal link and on RichTextToolbar link.

**Comment by yurabakhtin** [comment]
> From discussion: Set global var on click file handler and on Normal link and on RichTextToolbar link.

Commit https://github.com/humhub/humhub-prosemirror/pull/134/commits/8fc807b2524d8e2fe922e753ae23340f57770cff.

**Comment by luke-** [comment]
@yurabakhtin Why do we need this? 


> I have 2 problems:
> * `[Word.docx](file-guid:090a402a-50e1-464a-83fa-39250b261123)` - we should create some additional option to know the markdown link will be converted to link for viewing instead of current/default downloading url, maybe like `[Word.docx](file-guid:090a402a-50e1-464a-83fa-39250b261123 mode=view)` but I am not sure how it is possible from markdown parser, if it is, then we should add the `mode=view` for each link which is inserted by new plugin, but we need firstly solve the 1st point above.

I would prefer file links to always trigger the file handler modal. Or are there situations where this should not be the case?

**Comment by luke-** [comment]
@yurabakhtin It is ok if a modal always opens within the richtext, even if only one download is possible. 

In my tests, e.g. with the https://github.com/humhub/text-editor module, it did not add the created text file correctly in the rich text.

Otherwise it looks very good.

**Comment by luke-** [comment]
We also need to rearrange the menu: 
![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/84fece62-f905-4589-9cc8-562b3b2d9b1f)

**Comment by yurabakhtin** [comment]
> In my tests, e.g. with the https://github.com/humhub/text-editor module, it did not add the created text file correctly in the rich text.

@luke- For me it works correctly:

![text-editor](https://github.com/humhub/humhub-prosemirror/assets/6995524/2ca90661-a002-426e-b27d-eb7508f1e8a2)

**Comment by yurabakhtin** [comment]
> We also need to rearrange the menu: ![image](https://private-user-images.githubusercontent.com/4736168/301815553-84fece62-f905-4589-9cc8-562b3b2d9b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyMzk2OTUsIm5iZiI6MTcwNzIzOTM5NSwicGF0aCI6Ii80NzM2MTY4LzMwMTgxNTU1My04NGZlY2U2Mi1mOTA1LTQ1ODktOWNjOC01NjJiM2IyZDliMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDZUMTcwOTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDYyMWY0ZTU0NmI0N2FiNDcwMzkxMmI4ZmU3YWY3YzVjOGNiMmJjYWQ2ZjdjZGUxNTFmMmQ2MmUxOTc3MWYwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._S8mEdDSBsaor6_LBeV6STUjDLDnPhJV4XY9ttGwG2M)

@luke- Done in commit https://github.com/humhub/humhub-prosemirror/pull/134/commits/d696fd4a02ab4fec7df25f39628d77aa31e58eae, but please note there we don't use font-awesome icons, there svg path is used, so I could find this tool https://icomoon.io/app/#/select where I have found almost similar upload icon but it has a bit difference:

![icons](https://github.com/humhub/humhub-prosemirror/assets/6995524/de6be2ca-964b-4f50-af6d-85303de736dc)

**Comment by luke-** [comment]
> > In my tests, e.g. with the https://github.com/humhub/text-editor module, it did not add the created text file correctly in the rich text.
> 
> @luke- For me it works correctly:

@yurabakhtin  Now it also works for me as described by you. However, the file appears twice.

![image](https://github.com/humhub/humhub-prosemirror/assets/4736168/cf055a9f-2d7e-464e-afd9-9d73dcc24329)

**Comment by yurabakhtin** [comment]
@luke- I have removed the menu item "Image" yesterday as you requested on the screenshot, but what if user wants to add an image from some existing URL without uploading, maybe we should revert that?

![image-menu-item](https://github.com/humhub/humhub-prosemirror/assets/6995524/0fc6173b-5272-4a27-bdac-45b65d946bca)

**Comment by luke-** [comment]
> @luke- I have removed the menu item "Image" yesterday as you requested on the screenshot, but what if user wants to add an image from some existing URL without uploading, maybe we should revert that?
> 
@yurabakhtin Thanks for the hint.

We have discussed it again internally and decided to leave out the "picture" icon. In case of need, users can add the image via the Markdown Source Mode.

The line icon will also be removed also for now.

Please just comment out these icons

**Comment by luke-** [comment]
@yurabakhtin Ok thanks. Let me know when I can help. Maybe Serh kann also help.

Didn't we introduced some global var to determine which triggered the file upload? e.g. `isProsemirrorFileHandlerActive`?  Could we check this here? https://github.com/humhub/humhub/blob/master/protected/humhub/modules/file/resources/js/humhub.file.js#L533

**Comment by yurabakhtin** [comment]
@luke- Yes, it works, thanks for the advice.

- Commit https://github.com/humhub/humhub-prosemirror/pull/134/commits/984888b13682025078ef28b0c6ec353951184029
- `develop` PR https://github.com/humhub/humhub/pull/6847

**Comment by luke-** [comment]
@yurabakhtin Thanks it works as expected!
